openapi: "3.0.2"
info:
    title: NPPC-KANBAN TOOL
    version: "0.0.1"
security:
    - NPPC_AUTH: []
servers:
    - url: http://localhost:8000
components:
    responses:
        ToolNotFound:
            description: Tool not found
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error"
        Unauthorized:
            description: User cant be authorized
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/error"
    securitySchemes:
        NPPC_AUTH:
            type: apiKey
            in: header
            name: NPPC_AUTH
    schemas:
        error:
            description: NPPC Error object
            type: object
            properties:
                code: 
                    description: Error code
                    type: string
                message:
                    description: Full description 
                    type: string
        mlstring:
            description: Multi-language string object
            type: object
            required:
                - default
            properties:
                default:
                    description: Default value of string variable
                    type: string
                values:
                    description: Pairs lang=>string
                    type: array
                    items:
                        type: array
                        items:
                            maxItems: 2
                            minItems: 2
                            type: string
        tool:
            description: Tool for operation
            type: object
            properties:
                id:
                    type: string
                name:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
        material:
            description: Material or semi-final or auxiliary
            type: object
            properties:
                id:
                    type: string
                name:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
        operation:
            description: Final product
            type: object
            properties:
                id: 
                    type: string
                name:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                fullname:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                consistsof:
                    type: array
                    items:
                        $ref: "#/components/schemas/material"
                auxiliary:
                    type: array
                    items:
                        $ref: "#/components/schemas/material"
                tools:
                    type: array
                    items:
                        $ref: "#/components/schemas/tool" 
                cost: 
                    type: number
                duration:
                    type: number
                multiplication:
                    type: number
                result:
                    type: array
                    items:
                        oneOf:
                            - $ref: "#/components/schemas/material"
                            - $ref: "#/components/schemas/product"
        product:
            type: object
            properties:
                id:
                    type: string
                name:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                fullname:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                mdmcode:
                    type: string
                units:
                    type: array
                    items:
                        oneOf:
                            - $ref: "#/components/schemas/mlstring"
                            - type: string
        daterange:
            type: object
            properties:
                datepoint:
                    type: string
                left:
                    type: number
                right:
                    type: number
        multidate:
            type: object
            properties:
                estimated:
                    $ref: "#/components/schemas/daterange"
                baseline:
                    type: array
                    items:
                        type: array
                        items:
                            maxItems: 2
                            minItems: 2
                            oneOf:
                                - type: string
                                - $ref: "#/components/schemas/daterange"
        orderpriority:
            type: object
            properties:
                customer:
                    type: string
                manufacture:
                    type: string
        orderposition:
            type: object
            properties:
                sort:
                    type: number
                productid:
                    type: string
                product:
                    $ref: "#/components/schemas/product"
                count:
                    type: number
                measurement:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                constractdate:
                    $ref: "#/components/schemas/multidate"
                promisedate:
                    $ref: "#/components/schemas/multidate"
        order:
            type: object
            properties:
                number:
                    type: string
                priority:
                    $ref: "#/components/schemas/orderpriority"
                customerpo:
                    type: string
                contractdate:
                    $ref: "#/components/schemas/multidate"
                promisedate:
                    $ref: "#/components/schemas/multidate"
                products:
                    type: array
                    items:
                        $ref: "#/components/schemas/orderposition"
        worcenter:
            type: object
            properties:
                id:
                    description: Unique id of workcenter
                    type: string
                name:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                fullname:
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                workcenters:
                    type: array
                    items:
                        $ref: "#/components/schemas/worcenter"
                operations:
                    type: array
                    items:
                        $ref: "#/components/schemas/operation"
        factory:
            description: Factory object
            type: object
            required:
                - "id"
                - "name"
            properties:
                id:
                    description: Unique id of the Factory
                    type: string
                name:
                    description: Short name of factory
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                fullname:
                    description: Full name of factory
                    oneOf:
                        - $ref: "#/components/schemas/mlstring"
                        - type: string
                workcenters: 
                    type: array
                    items:
                        $ref: "#/components/schemas/worcenter"
    parameters:
        factoryid:
            description: Uniq id of factory
            name: factoryid
            schema:
                type: string
            in: path
            required: true
        toolid:
            description: Uniq id of tool
            name: toolid
            schema:
                type: string
            in: path
            required: true
        materialid:
            description: Uniq id of material
            name: materialid
            schema:
                type: string
            in: path
            required: true
        limit-maxitems:
            description: If request has a few objects this param restricts the count of records in responce
            name: limit-maxitems
            in: query
            required: false
            schema:
                type: number
        limit-offset:
            description: If request has a few objects this param asks offset first record inresponce
            name: limit-offset
            in: query
            required: false
            schema:
                type: number
        results.materialref:
            description: Be used for operation requests
            name: results.materialref
            in: query
            required: false
            schema:
                type: string
        count:
            description: count of Material
            name: count
            in: query
            required: true
            schema:
                type: number
paths:
    /factory/{factoryid}:
        get:
            description: Returns all information about factory by its uniq id
            operationId: factory
            parameters:
                - $ref: "#/components/parameters/factoryid"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/factory'
                404:
                    description: Factory not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
    /factory/{factoryid}/orders:
        get:
            description: Returns all orders of the factory
            operationId: orders
            parameters:
                - $ref: "#/components/parameters/factoryid"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/order'
                404:
                    description: Factory not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
    /factory/{factoryid}/tool/{toolid}:
        get:
            description: Returns all information about tool by its uniq id
            operationId: tool
            parameters:
                - $ref: "#/components/parameters/factoryid"
                - $ref: "#/components/parameters/toolid"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/tool'
                400:
                    description: Factory not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
    /factory/{factoryid}/material/{materialid}:
        get:
            description: Returns all information about material or product or semi-final by its uniq id
            operationId: material
            parameters:
                - $ref: "#/components/parameters/factoryid"
                - $ref: "#/components/parameters/materialid"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/material'
                400:
                    description: Factory not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
    /factory/{factoryid}/material/{materialid}/route:
        get:
            description: Creates and returns tree of routes for material or product or semi-final by its uniq id
            operationId: route
            parameters:
                - $ref: "#/components/parameters/factoryid"
                - $ref: "#/components/parameters/materialid"
                - $ref: "#/components/parameters/count"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/material'
                400:
                    description: Factory not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
    /factory/{factoryid}/operations:
        get:
            description: Returns all operations of factory
            operationId: operations
            parameters:
                - $ref: "#/components/parameters/factoryid"
                - $ref: "#/components/parameters/results.materialref"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/material'
                400:
                    description: Factory not found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
